mainapp/urls.py
from django.urls import path

from mainapp.views import AccommodationDetailView, AccommodationListView

app_name = 'mainapp'

urlpatterns = [
    path('', AccommodationListView.as_view(), name='index'),
    path('accommodation_detail/<int:pk>/', AccommodationDetailView.as_view(), name='accommodation')
]

market_prj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import MainTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainTemplateView.as_view(), name='main'),
    path('accommodations/', include('mainapp.urls', namespace='acc'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


# Create your models here.
class Country(models.Model):
    name = models.CharField(verbose_name='название', max_length=64, unique=True)
    desc = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    created_at = models.DateTimeField(verbose_name='создана', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='обновлена', auto_now=True)

    def __str__(self):
        return self.name


class Region(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='страна')
    name = models.CharField(verbose_name='название', max_length=64, unique=True)
    desc = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    created_at = models.DateTimeField(verbose_name='создана', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='обновлена', auto_now=True)

    def __str__(self):
        return f'{self.name} | {self.country.name}'


class Accommodation(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='страна')
    region = models.ForeignKey(Region, on_delete=models.CASCADE, verbose_name='регион')
    name = models.CharField(verbose_name='наименование', max_length=128)
    image = models.ImageField(verbose_name='изображение', upload_to='accommodation_img', blank=True)
    short_desc = models.TextField(verbose_name='краткое описание', blank=True)
    full_desc = models.TextField(verbose_name='полное описание', blank=True)
    availability = models.PositiveIntegerField(verbose_name='количество свободных номеров')
    price = models.DecimalField(verbose_name='стоимость', max_digits=8, decimal_places=2)
    room_desc = models.TextField(verbose_name='описание комнаты', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    created_at = models.DateTimeField(verbose_name='создана', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='обновлена', auto_now=True)

    def __str__(self):
        return f'{self.name} | {self.country.name}'

    @staticmethod
    def get_items():
        return Accommodation.objects.filter(is_active=True).order_by('country', 'region', 'name')

mainapp/views.py
# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView

from mainapp.models import Accommodation


class MainTemplateView(TemplateView):
    template_name = 'mainapp/index.html'


class AccommodationListView(ListView):
    template_name = 'mainapp/accommodations.html'

    def get_queryset(self):
        return Accommodation.get_items()


class AccommodationDetailView(DetailView):
    model = Accommodation
    template_name = 'mainapp/accommodation_details.html'

mainapp/templates/mainapp/accommodation_details.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <div class="media ">
            <img src="{{ accommodation.image.url }}"
                 class="img-fluid mt-2 col-lg-offset-4" alt="Responsive image"
                 style="height: 300px">
            <div class="ml-1 container-fluid">
                <div class="align-content-lg-between text-center">
                    <h1 class="mt-3 ml-3">{{ accommodation.name|title }}</h1>
                    <br>
                    <p>месторасположение: {{ accommodation.region|title }}</p>
                    <br>
                    <p>стоимость за сутки: {{ accommodation.price }}</p>
                    <br><br><br><br>
                </div>
            </div>
        </div>
        <div class="mt-3">
            <h3>Описание</h3>
            {{ accommodation.description|title }}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/accommodations.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-3">
        <div class="row centered">
            {% for offer in object_list %}
                <div class="card  col-lg-4" style="width: 16rem;
                display: flex">
                    <img src="{{ offer.image.url }}"
                         class="card-img-top filters__img" alt="{{ offer.name }}">
                    <div class="card-body fa fa-align-justify">
                        <h5 class="card-title">{{ offer.name|title }}</h5>
                        <p class="card-text">{{ offer.region|title }}</p>
                        <p class="card-text">{{ offer.price }} за сутки.</p>
                        <a href="{% url 'acc:accommodation' offer.pk %}"
                           class="btn btn-danger">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
        <title>TravelMarket</title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/style.css' %}">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    {% endblock %}
    {% block js %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
    {% endblock %}


</head>
<body>
<div class="container">

    {% block menu %}
        {% include 'mainapp/includes/inc_menu.html' %}
    {% endblock %}

    {% block list %}{% endblock %}

    {% block content %}{% endblock %}

</div>
</body>
<footer>
    {% block footer %}
        {% include 'mainapp/includes/inc_footer.html' %}
    {% endblock %}
</footer>
</html>

mainapp/templates/mainapp/includes/inc_footer.html
<div class="page-footer font-small unique-color-dark">
    <div class="container">
        <div class="row py-4 d-flex align-items-center">
            <div class="col-md-6 col-lg-5
                    text-center text-md-left mb-4 mb-md-0">
                <h6 class="mb-0 text-center">
                    И весь мир у вас на ладони</h6>
            </div>
            <div class="col-md-6 col-lg-7 text-center text-md-right">

                <!-- Facebook -->
                <a class="fb-ic">
                    <i class="fab fa-facebook-f white-text mr-4"> </i>
                </a>
                <!-- Twitter -->
                <a class="tw-ic">
                    <i class="fab fa-twitter white-text mr-4"> </i>
                </a>
                <!-- Google +-->
                <a class="gplus-ic">
                    <i class="fab fa-google-plus-g
                            white-text mr-4"> </i>
                </a>
                <!--Linkedin -->
                <a class="li-ic">
                    <i class="fab fa-linkedin-in white-text mr-4"> </i>
                </a>
                <!--Instagram-->
                <a class="ins-ic">
                    <i class="fab fa-instagram white-text"> </i>
                </a>

            </div>
        </div>
    </div>
    <div class="container text-center text-md-left mt-5">
        <div class="row mt-3">
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold">О нас</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0
                         d-inline-block mx-auto" style="width: 60px;">
                <p>Thank you for patience and understanding.</p>

            </div>
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold">Страны</h6>
                <hr class="deep-black accent-2 mb-4 mt-0
                        d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold">
                    Полезные ссылки</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0
                        d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
            </div>
            <div class="col-md-4 col-lg-3
                    col-xl-3 mx-auto mb-md-0 mb-4">
                <hr class="deep-purple accent-2 mb-4 mt-0
                        d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <i class="fas fa-home mr-3"></i>
                    Moscow, Russia</p>
                <p>
                    <i class="fas fa-envelope mr-3"></i>
                    user@mail.ru</p>
                <p>
                    <i class="fas fa-phone mr-3"></i>
                    + 01 000 567 88</p>
                <p>
                    <i class="fas fa-print mr-3"></i>
                    + 01 000 567 89</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3">&copy; 2020 Copyright:
        <a href="#">thereisnomercy.com</a>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_menu.html
<div class="">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="{% url 'main' %}">TravelMarket</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'acc:index' %}">
                        забронировать размещение</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'acc:index' %}">
                <input class="form-control mr-sm-1"
                       type="search" placeholder="Поиск на сайте" aria-label="Search"
                       name="search">
                <button class="btn btn-outline-danger my-2 my-sm-0 disabled"
                        type="submit">Поиск
                </button>
            </form>
        </div>
    </nav>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="">
        <div id="carouselExampleFade" class="carousel slide
        carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/thai.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/beach.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/sands.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade"
               role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"
                      aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next"
               href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon"
                      aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="card nav-item">
            <div class="card-body">
                <h5 class="card-title">Отдых,
                    который Вы заслужили</h5>
                <p class="card-text">Лучшие и самые дешёвые
                    предложения на рынке от поставщиков</p>
                <a class="btn btn-danger"
                   href="{% url 'acc:index' %}">Смотреть размещение</a>
            </div>
        </div>
    </div>
{% endblock %}